site_name: Palomero Lab How-To
site_url: https://palomerolab.github.io/how-to/
repo_url: https://github.com/palomeroLab/how-to/
edit_uri: blob/main/docs/
site_description: A collection of how-to guides for the Palomero Lab
site_author: Ryan D. Najac
copyright: <a href="https://www.cuimc.columbia.edu/"><img src="https://github.com/PalomeroLab/how-to/blob/main/assets/CUIMC_Horizontal_Blue.png?raw=true" alt = "CUIMC Logo"></a><br>Copyright &copy; 2024 <a href="https://www.columbia.edu/">Columbia University</a>

# Put internal documenets here
not_in_nav: /private

theme:
  name: readthedocs
  custom_dir: custom_theme/
  prev_next_buttons_location: top

markdown_extensions:
  - markdown_gfm_admonition

plugins:
  - search
  - macros

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css
  - style.css

extra_javascript:
  - extra.js
